### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by Just1bridou** [Listenbourg/Traduction#2]
Je trouve qu'il y a des problèmes dans le nouveau css :

**Avant:**
<img width="975" alt="screen1" src="https://user-images.githubusercontent.com/45208166/201606292-53d038a9-9d3d-4c18-89a2-79b594f742a1.png">
**Après:**
<img width="975" alt="screen2" src="https://user-images.githubusercontent.com/45208166/201606296-7d66034d-8896-4d31-b04b-4a1b5c5664d5.png">

- On a plus de margin qu'avant, ce qui est problématique quand on a un petit écran
- Quand on hover un mot le texte s'affiche trop bas
- Quand on hover un mot, la couleur du background n'existe plus, ça apportait un plus pour différencier les mots

**Comment by Just1bridou** [comment]
Je remarque aussi que le bouton pour écouter la traduction à disparu 🤔

**Comment by NonozgYtb** [comment]
J'ai tout fixé dans le PR #3 ! 
@Just1bridou
